export const API_GET_TYPEOFDEVICE = 'API_GET_TYPEOFDEVICE';
export const API_STORE_TYPEOFDEVICE = 'API_STORE_TYPEOFDEVICE';
export const API_GET_LOGIN = 'API_GET_LOGIN';
// export const API_TOKEN_LOGIN = 'API_GET_LOGIN';
export const API_STORE_LOGIN = 'API_STORE_LOGIN';
export const API_STORE_COSO = 'API_STORE_COSO';
export const STORE_DEVICE = 'STORE_DEVICE';
export const STORE_MAC = 'STORE_MAC';
